### ISSUE TITLE
doesn't work with Node.js 4 LTS

### ISSUE THREAD

**Issue by diasdavid** [orbitdb/ipfs-log#101]

**Comment by haadcode** [comment]
Hi, we've moved to use latest JavaScript functionality (eg. await) and as such Node.js 4 is not supported anymore. However, there's an [ES5 build in the repo](https://github.com/orbitdb/ipfs-log/tree/master/lib/es5) that you can require() in a program that runs on Node.js 4. The ES5 build is also available when installed from npm.

Hope this works for your needs. Feel free to re-open the issue if it doesn't.
