### ISSUE TITLE
preparations for js-ipfs 0.29.0

### ISSUE THREAD

**Issue by diasdavid** [orbitdb/ipfs-log#124]
I've run the tests of this module in preparation for https://github.com/ipfs/js-ipfs/issues/1320.

All of the tests pass, however, note that the PubSub API did change, consider updating carefully. See change log in the release issue https://github.com/ipfs/js-ipfs/issues/1320

**Comment by haadcode** [comment]
Thank you @diasdavid for the heads up, wasn't able to pull this one in, but we're now up to date with the latest (as per https://github.com/orbitdb/ipfs-log/issues/129).
