### ISSUE TITLE
Add benchmarks runner and incorporate performance testing with CI/PRs

### ISSUE THREAD

**Issue by mistakia** [orbitdb/ipfs-log#140]
Building on @haadcode's suggestion in orbitdb/ipfs-log#136, I would be down to help setup benchmarks for all of the methods and incorporate performancing testing with CircleCI to be able to better evaluate PRs in the future.

**Comment by haadcode** [comment]
Proper benchmarking suite would be sweet! Go for it 👍 Let us know if there's anything we can help with.
