### ISSUE TITLE
Constructor arguments (one vs many)

### ISSUE THREAD

**Issue by mistakia** [orbitdb/ipfs-log#156]
Just wanted to start a conversation about potentially moving away from having a large number of arguments when you have a mix of both optional and required arguments. Looking at it from a readability and functional perspective, I see the following benefits of moving toward a single argument object and avoiding instance creation that looks like this:

https://github.com/orbitdb/ipfs-log/blob/21bd045b4b4a27c59844ec091844ce9bdc5f88ed/benchmarks/benchmark-join-signed.js#L70

1. For me, named parameters are easier to remember than the argument order when there are as many as 7 arguments. It can also lead to greater readability as its not explicit what 'A' is in the above example
2. Potentially cleaner and less error prone use of optional parameters — similar to the first argument, you have to keep track of the argument order to properly place variables and `null`.
3. Easier to add and remove arguments.

**Comment by mistakia** [comment]
Another option to consider is having a required argument for ipfs and an object for the remaining optional arguments (entries, keys, key, id, entries, heads, clock).

**Comment by thiagodelgado111** [comment]
I'd agree with that, I guess something this: `new Log(ipfs, id, accessController, identity, options)`. I'd also like to introduce the concept of Factories, in fact, I've done a PR with that maybe we can do the refactoring you're proposing there too? cc @mistakia

**Comment by mistakia** [comment]
I agree with all of those suggestions.

**Comment by aphelionz** [comment]
Closing this for now as we would like to prefer an explicit function signature.
