### ISSUE TITLE
Traversal Improvements

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/ipfs-log#201]
From: https://github.com/ipfs/dynamic-data-and-capabilities/issues/50

* Provide a way to efficiently and incrementally traverse the log. If I request the last 5 entries, there should be as less traversal and I/O as possible to accomplish that. Also, it should be able to have some kind of resume of the traversal, for pagination use-cases.
* Ensure that the traversal of the tree happens concurrently, as much as possible. We can obviously improve later on.

**Comment by aphelionz** [comment]
@satazor We just merged in a version of the log.values function that traverses the log. Have a look and let me know where we should go from there.

**Comment by aphelionz** [comment]
@satazor Friendly reminder to review the code currently in two places and let me know if this is sufficient:

* https://github.com/orbitdb/ipfs-log/blob/master/src/log.js#L128
* https://github.com/orbitdb/ipfs-log/blob/master/src/log.js#L171

**Comment by satazor** [comment]
Yes I will review those as soon as I get back from holidays, which is Jan 4th. If I have the time, I will do it sooner.

**Comment by aphelionz** [comment]
Ok cool, enjoy the holidays :)

**Comment by satazor** [comment]
@aphelionz I think the lines you linked are pointing to the wrong lines because commits were made in master meanwhile.

**Comment by aphelionz** [comment]
oops! updated.

**Comment by satazor** [comment]
I think `traverse` is what I need and it seems that it respects the `amount` efficiently. Perhaps, we are missing making it officially part of the public API.

**Comment by aphelionz** [comment]
Yes, I'm working on documentation that will clarify that. I'll close this ticket for now.
