### ISSUE TITLE
Pass in own sorting / tie breaking function

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/ipfs-log#204]
From: https://github.com/ipfs/dynamic-data-and-capabilities/issues/50

Remove lamport clocks as the implicit tie breaker and instead make it a configuration. The reason is that lamport clocks occupy a lot of space when there are a lot of replicas, which is unnecessary in some use-cases, such as the one in Discussify

**Comment by aphelionz** [comment]
cc @satazor

**Comment by aphelionz** [comment]
@satazor Which issues will you be tackling first? I'm going to be working on these as well, starting with this one.

**Comment by satazor** [comment]
In parallel to all these issues, I’m leading an identity effort on the IPFS WG as well as some other stuff stuch as recording a video about the status of discussify and preparing a workshop that I will be giving next week. This to say that I will be doing a lot of stuff “concurrently”.

I need to first analyze the condebase and ideally I would pick an easier one first. Which one do you think it’s the best?

**Comment by aphelionz** [comment]
Great question.

What about one of these two:
* https://github.com/orbitdb/ipfs-log/issues/200
* https://github.com/orbitdb/ipfs-log/issues/203

**Comment by satazor** [comment]
#200 seems easy, but it will be a breaking change. Is it a problem to start with this one?

**Comment by aphelionz** [comment]
Not a problem at all. Personally I'm excited to see what comes of it w/r/t CBOR.

**Comment by haadcode** [comment]
@aphelionz I believe @satazor wanted something like described in https://github.com/ipfs/dynamic-data-and-capabilities/issues/50#issuecomment-440245307. As to a specific function, dunno exactly what to compare :)

**Comment by aphelionz** [comment]
I just made it the last argument of the `Log` constructor. I'll just make a PR now and y'all can have at it :)

**Comment by aphelionz** [comment]
@satazor @haadcode https://github.com/orbitdb/ipfs-log/pull/209
