### ISSUE TITLE
Tests not passing on clean install

### ISSUE THREAD

**Issue by satazor** [orbitdb/ipfs-log#206]
OS: MacOSX Sierra

Just cloned the repo, did `npm i` and `npm t` . The tests fail with the following:

```
 "before all" hook:
     Error: Lock FcntlFlock of /Users/andrecruz/Work/moxy/protocol-labs/orbitdb/ipfs-log/ipfs/ipfs-log/tests/daemon11544862521094/repo.lock failed: EINVAL, Invalid argument
```

Does anyone experience this problem before?

**Comment by haadcode** [comment]
@satazor haven't seen that before, but looks like the IPFS data repo is already in use. I just checked master and ran `npm i && npm test` and all tests pass correctly. I'm on OSX and node.js v10.13.0.

What node version are you on? You could try also running `make rebuild` see if that makes any difference (removes `package-lock.json` before running `npm i `).

**Comment by satazor** [comment]
@haadcode unfortunately, `make rebuild` didn't help. I will investigate.

**Comment by satazor** [comment]
I was using node 11. Downgrading to node 10 fixed it. What node version are you running @haadcode ?

**Comment by aphelionz** [comment]
Good to know! Two questions:

1. Is there anything specifically in Node 11 you're using to interact with Orbit? Maybe there are breaking changes in `fs` or sometihng
2. We should make a note for people to use LTS versions of Node with Orbit when possible. Where mght be the best place to put that.

cc @haadcode

**Comment by satazor** [comment]
I found the culprit: https://github.com/dignifiedquire/lock-me/issues/4

This has been solved in IPFS by switching the library that performs the locking but they didn’t released a new version yet.
