### ISSUE TITLE
importing identity

### ISSUE THREAD

**Issue by sirpy** [orbitdb/ipfs-log#294]
I'm using this on heroku and there's no persistant storage
i've asked this on orbit-db identity provider but no answer
https://github.com/orbitdb/orbit-db-identity-provider/issues/54

is there a way to simply import an identity that is saved on some other remote storage?

**Comment by sirpy** [comment]
can anyone  from the mainters comment on this?
pointer on how to implement?

**Comment by aphelionz** [comment]
Hi sorry for the delay, @sirpy . The maintainer who knows the most about that system, @shamb0t is on a vacation right now. Thanks for your patience and we'll get back to you ASAP.

**Comment by shamb0t** [comment]
Hey @sirpy take a look at my comment in https://github.com/orbitdb/orbit-db-identity-provider/issues/54#issuecomment-587302358, hope that helps

**Comment by sirpy** [comment]
@shamb0t we would like to use an external source or to import and identity to the keystore
