### ISSUE TITLE
ipfs-log@4.6.4 is breaking old orbit-db releases

### ISSUE THREAD

**Issue by oed** [orbitdb/ipfs-log#310]
We've noticed that `cids@1.0.0` is being pulled in from `orbit-db-io` into this package. This is a breaking change and the v1.0 of cids is not compatible with older versions. Since only the patch version of this package was updated it's causing issues upstream.

I would recommend that:
1. `ipfs-log@4.6.5` is released which rolls back the update to cids
2. `ipfs-log@5.0.0´ is released which would contain the new cids version

**Comment by aphelionz** [comment]
Good call @oed, will do ASAP

**Comment by oed** [comment]
Thank you @aphelionz 🙏 Some of our users have been seeing issues because of this :)

**Comment by aphelionz** [comment]
- [x] hotfix/v4.6.5 branch pushed and v4.6.5 published to npm
- [ ] v5.0.0 will be pushed to master and published to the `@next` tag. Tests that were passing two days ago are now failing :P

**Comment by aphelionz** [comment]
idk, looks like the go-ipfs tests are messed up now. @oed at least let me know if 4.6.5 fixes the issue for you

**Comment by oed** [comment]
Looks good based on the dependency tree.
