### ISSUE TITLE
Time to remove `lib/es5`?

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/ipfs-log#333]
What do we think

**Comment by haadcode** [comment]
I think so, yeah 👍 

It was added back in the day, when es5->es6 transition was still happening. We're past that.

**Comment by aphelionz** [comment]
Awesome

**Comment by CSDUMMI** [comment]
If this is truely the case, then my [PR](https://github.com/orbitdb/ipfs-log/pull/339) is not necessary right?

What are the steps necessary to remove `lib/es5`?

**Comment by aphelionz** [comment]
They are generated via a build step inside `package.json`. Removing that and the `lib/es5` folder itself should be sufficient.

**Comment by haadcode** [comment]
This was done in #363
