### ISSUE TITLE
Support signed messages

### ISSUE THREAD

**Issue by haadcode** [orbitdb/ipfs-log#34]

**Comment by haadcode** [comment]
Dropping this from uPort integration milestone as this is not *needed* to reach the milestone. Definitely want to do this at some point though.

**Comment by haadcode** [comment]
THere's a prototype for ipfs-log here: https://github.com/haadcode/ipfs-log/commit/25d0c5f379a9acf558eb24aaec56da62eb2acb62

**Comment by haadcode** [comment]
I would like to bump this for Q1/17. This is the basic building block for access-control (permissions) and has been asked about / requested by multiple people over the past months. I would like to finally get to this.

**Comment by mitar** [comment]
I opened this issue for a similar need in [luckychain code](https://github.com/luckychain/lucky): https://github.com/ipfs/interface-ipfs-core/issues/120

**Comment by haadcode** [comment]
Posted a comment re. this here https://github.com/orbitdb/orbit-db/issues/57#issuecomment-291101763

**Comment by haadcode** [comment]
Working on this now. WIP branch at https://github.com/haadcode/ipfs-log/tree/feat/write-logs.

**Comment by haadcode** [comment]
You can check the spec for intended usage: https://github.com/haadcode/ipfs-log/blob/feat/write-logs/test/signed-log.spec.js#L47

**Comment by haadcode** [comment]
This is now finally done! 🎉 Release `4.0.0` brings signed logs.

**Comment by mitar** [comment]
How do you do it without https://github.com/ipfs/interface-ipfs-core/issues/120? Where are keys stored?
